name: Build and Test

permissions:
  contents: read

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Download Dependencies
        run: go mod download

      - name: Verify Dependencies
        run: go mod verify

      - name: Run tests
        run: go test -v ./...

      - name: Build
        env:
          SOURCE_DATE_EPOCH: ${{ github.event.head_commit.timestamp || github.event.pull_request.head.repo.pushed_at }}
        run: go build -v -o containerfile-updater ./...

      - name: Digest
        run: sha256sum containerfile-updater
