name: Test Container Build and Reproducibliity

on:
  pull_request:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  GITHUB_REPOSITORY: ${{ github.repository }}

jobs:
  build:
    name: Matrix Build (${{ matrix.build-id }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build-id: [1, 2]

    outputs:
      version: ${{ steps.version.outputs.version }}

    steps:
    - name: Checkout code
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      with:
        fetch-depth: 0

    - name: Set Image name
      run: |
        echo "IMAGE_NAME=${GITHUB_REPOSITORY,,}" >> ${GITHUB_ENV}

    - name: Setup Docker
      uses: docker/setup-docker-action@3fb92d6d9c634363128c8cce4bc3b2826526370a # v4
      with:
        daemon-config: |
          {
            "debug": true,
            "features": {
              "containerd-snapshotter": true
            }
          }

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3

    - name: Generate build metadata
      id: version
      run: |
        version=$(git describe --tags --always --dirty 2>/dev/null || echo "dev")
        echo "VERSION=${version}" >> ${GITHUB_ENV}
        echo "OUT_DIR=build-${{ matrix.build-id }}" >> ${GITHUB_ENV}
        echo "version=${version}" >> ${GITHUB_OUTPUT}
        echo "Version: $VERSION"


    - name: Build image
      run: |
        make image

    - name: Generate image digests
      run: |
        echo "Build ${{ matrix.build-id }} digests:"
        make show-image-digests

    - name: Upload build artifact
      uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5
      with:
        name: build-${{ matrix.build-id }}
        path: "build-${{ matrix.build-id }}"
        retention-days: 7

  verify:
    name: Verify Deterministic Builds
    runs-on: ubuntu-latest
    needs: build
    outputs:
      build-verified: ${{ steps.compare.outputs.verified }}

    steps:
    - name: Checkout code
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      with:
        fetch-depth: 0

    - name: Download build artifacts
      uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5
      with:
        pattern: build-*
        merge-multiple: false

    - name: Compare Images
      id: compare
      run: |
        echo "Comparing digests from both builds..."

        echo "Build 1 digests:"
        cat build-1/digests.txt
        echo
        echo "Build 2 digests:"
        cat build-2/digests.txt
        echo

        if cmp -s build-1/digests.txt build-2/digests.txt; then
          echo "✅ Build outputs are identical - deterministic build verified!"
          echo "verified=true" >> $GITHUB_OUTPUT
        else
          echo "❌ Build outputs differ - deterministic build failed!"
          echo "Differences:"
          diff build-1/digests.txt build-2/digests.txt || true
          echo "verified=false" >> $GITHUB_OUTPUT
          exit 1
        fi

        # Generate summary for Github Action
        make github-digest-summary DIGESTS1=build-1/digests.txt DIGESTS2=build-2/digests.txt >> ${GITHUB_STEP_SUMMARY}
